// Problem 2
/*
	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

class Problem_2 {
	public static void main(String[] args) {
		int fib_num_1 = 1, fib_num_2 = 2, fib_num_3 = 0;
		int total_sum = 0;
		total_sum += fib_num_2;
		
		while (fib_num_3 <= 4000000) {
			if (fib_num_3 % 2 == 0) total_sum += fib_num_3;
			fib_num_3 = fib_num_1 + fib_num_2;
			fib_num_1 = fib_num_2;
			fib_num_2 = fib_num_3;
		}
		
		System.out.printf("%d", total_sum);
	}
}